// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

"use client";

import "./globals.css";
import "../i18n";
import { ReactNode } from "react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { Providers } from "./providers";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <Providers>
        <body className="min-h-screen flex flex-col">
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </body>
      </Providers>
    </html>
  );
}

// import { NextSeo, type NextSeoProps } from 'next-seo';
// import { NextSeoProps } from 'next-seo/pages';
// import React from 'react';

// interface PrimaryLayoutProps extends React.PropsWithChildren {
//   seo: NextSeoProps;
// }

// export const PrimaryLayout = ({ seo, children }: PrimaryLayoutProps) => {
//   return (
//     <>
//       <NextSeo noindex={true} nofollow={true} {...seo} />
//       <div className="min-h-screen">
//         <Header collections={data} />
//         {children}
//       </div>
//       <Footer />
//     </>
//   );
// };
